# Data Preprocessing 

In [58]:
import pandas as pd 
import numpy as np 
import tensorflow as tf

In [59]:
df = pd.read_csv('churn_data.csv')

In [60]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:,-1].values

In [61]:
cols = df.select_dtypes(include=['object'])
for col in cols.columns.values:
    df[col] = df[col].fillna('')

In [62]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [63]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding categorical data

### Label Encoding the "Gender" column

In [64]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:,2])

In [65]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One Hot Encoding the "Geography" column

In [66]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [67]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


## Splitting the dataset

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Feature Scaling

In [69]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the ANN

In [70]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [71]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train,y_train, batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.6467 - accuracy: 0.6289
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4929 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4524 - accuracy: 0.7959
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4314 - accuracy: 0.8016
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4198 - accuracy: 0.8062
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4097 - accuracy: 0.8163
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3980 - accuracy: 0.8257
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3855 - accuracy: 0.8376
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3755 - accuracy: 0.8411
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3682 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3299 - accuracy: 0.8654
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3291 - accuracy: 0.8652
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8656
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3288 - accuracy: 0.8643
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3291 - accuracy: 0.8660
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3291 - accuracy: 0.8659
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3290 - accuracy: 0.8662
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3288 - accuracy: 0.8652
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3286 - accuracy: 0.8655
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3287 - accuracy: 

In [74]:
scores = model.evaluate(X_test, y_test, verbose=1)

63/63 [==============================] - 0s 2ms/step - loss: 0.3275 - accuracy: 0.8640


In [78]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
cm = confusion_matrix(y_test, y_pred)
print(cm)



63/63 [==============================] - 0s 2ms/step
[[1515   80]
 [ 192  213]]
